export type VisualizerRenderer = 'tree-or-graph' | 'matrix';

export const VISUALIZER_REGISTRY: Record<string, { renderer: VisualizerRenderer; status: 'interactive'; input: string }> = {
  avl:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, bst:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, redblack:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, heap:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, btree:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, segment:{renderer:'tree-or-graph',status:'interactive',input:'numbers'},
  trie:{renderer:'tree-or-graph',status:'interactive',input:'words'}, bfsdfs:{renderer:'tree-or-graph',status:'interactive',input:'graph'}, dijkstra:{renderer:'tree-or-graph',status:'interactive',input:'weighted graph'}, bellmanford:{renderer:'tree-or-graph',status:'interactive',input:'weighted graph'}, mst:{renderer:'tree-or-graph',status:'interactive',input:'weighted graph'}, tarjan:{renderer:'tree-or-graph',status:'interactive',input:'directed graph'}, toposort:{renderer:'tree-or-graph',status:'interactive',input:'DAG'}, maxflow:{renderer:'tree-or-graph',status:'interactive',input:'capacity graph'},
  knapsack:{renderer:'matrix',status:'interactive',input:'items and capacity'}, lcs:{renderer:'matrix',status:'interactive',input:'two strings'}, floydwarshall:{renderer:'matrix',status:'interactive',input:'weighted graph'}, matrixchain:{renderer:'matrix',status:'interactive',input:'dimensions'}, editdistance:{renderer:'matrix',status:'interactive',input:'two strings'}, bitmaskdp:{renderer:'matrix',status:'interactive',input:'distance matrix'}, nqueens:{renderer:'matrix',status:'interactive',input:'board size'}, sparsetable:{renderer:'matrix',status:'interactive',input:'numbers'},
  dsu:{renderer:'tree-or-graph',status:'interactive',input:'union operations'}, kmp:{renderer:'tree-or-graph',status:'interactive',input:'text and pattern'}, suffixarray:{renderer:'tree-or-graph',status:'interactive',input:'text'}, hashing:{renderer:'tree-or-graph',status:'interactive',input:'keys'}, fenwick:{renderer:'tree-or-graph',status:'interactive',input:'numbers'}, amortized:{renderer:'tree-or-graph',status:'interactive',input:'operation sequence'}, fibonacci:{renderer:'tree-or-graph',status:'interactive',input:'heap operations'}, rabinkarp:{renderer:'tree-or-graph',status:'interactive',input:'text and pattern'}, convexhull:{renderer:'tree-or-graph',status:'interactive',input:'points'}, npcomplete:{renderer:'tree-or-graph',status:'interactive',input:'problem reduction'}, skiplist:{renderer:'tree-or-graph',status:'interactive',input:'keys'}, splay:{renderer:'tree-or-graph',status:'interactive',input:'access sequence'}, radixsort:{renderer:'tree-or-graph',status:'interactive',input:'non-negative integers'}, zalgo:{renderer:'tree-or-graph',status:'interactive',input:'text'}, manacher:{renderer:'tree-or-graph',status:'interactive',input:'text'}, bloomfilter:{renderer:'tree-or-graph',status:'interactive',input:'keys'},
};

export const hasDedicatedVisualizer = (key: string) => Boolean(VISUALIZER_REGISTRY[key]);
export const usesMatrixRenderer = (key: string) => VISUALIZER_REGISTRY[key]?.renderer === 'matrix';
